Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -54,12 +54,15 @@ jobs:
           cd $GITHUB_WORKSPACE
           ./build.sh
       
-      - name: Build executable 2
-        if: success() || failure()
-        run: |
-          set -x
-          cd $GITHUB_WORKSPACE
-          /mingw32/bin/mingw32-make
+#      - name: Build executable 2
+#        if: success() || failure()
+#        run: |
+#          set -x
+#          cd $GITHUB_WORKSPACE
+#          /mingw32/bin/mingw32-make
+
+      - name: Check the output
+        run: ls -R $GITHUB_WORKSPACE
 
       - name: Get current date
         id: date
@@ -83,6 +86,6 @@ jobs:
           GITHUB_TOKEN: ${{ github.token }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: $GITHUB_WORKSPACE\wx-config.exe
+          asset_path: $GITHUB_WORKSPACE/wx-config.exe
           asset_name: wx-config.exe
           asset_content_type: application/exe
